### ISSUE TITLE
Add the open sourced Istio Handbook by ServiceMesher community

### ISSUE THREAD

**Issue by rootsongjc** [askmeegs/learn-istio#3]
The ServiceMesher community is co-writing an open-source Istio ebook, the book is in Chinese, I wonder if it can be included in your list?

There are huge amount of Istio end-users in China, we'd like to see some Chinese materials in this list also.

https://github.com/servicemesher/istio-handbook

**Comment by meganokeefe** [comment]
Added! Thanks, Jimmy - and definitely happy to add any other Chinese materials to the list.
